# betsvr Cloudflare Tunnel config (separate tunnel from lmsvr)
#
# After creating a new tunnel, set:
# - tunnel: <TUNNEL_ID>
# - credentials-file: /etc/cloudflared/credentials.json
#
# Then route DNS:
#   cloudflared tunnel route dns betsvr-bet bet.laserpointlabs.com

tunnel: c1e92e91-ce74-4b5c-9949-783fdfe56670
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: bet.laserpointlabs.com
    service: http://bet_frontend:80
  - service: http_status:404
